#PARAMS_BEG
OutputFile=ntuple_@@TAG_@@IDX.root
OutputPrefix=
MaxEvents=@@MAXEVENTS
DrGenMatchMin=0.1
IsMC=1
GenParticlePtMin=4.0
DoGenMatching=1
SCAbsEtaMin=0.0
SCAbsEtaMax=1.4
InputTreeName=Ntuples/EventTree
ReportEvery=500
#PARAMS_END
#FILELIST_BEG
@@FNAMES
#FILELIST_END
