#PARAMS_BEG
OutputFile=ntuple_@@TAG_@@IDX.root
OutputPrefix=
MaxEvents=@@MAXEVENTS
DrGenMatchMin=0.1
IsMC=1
GenParticlePDGID=111
GenParticleIsStable=0
GenParticlePtMin=4.0
DoGenMatching=1
SCAbsEtaMin=1.4
SCAbsEtaMax=2.5
InputTreeName=Ntuples/EventTree
ReportEvery=50
#PARAMS_END
#FILELIST_BEG
@@FNAMES
#FILELIST_END
